name: Docker Build and Run Locally

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: self-hosted 

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Build Docker image
      - name: Build Docker image
        run: sudo docker build -t node-server .

      # Step 4: Stop and Remove Existing Container
      - name: Stop Existing Container (if any)
        run: |
          sudo docker stop node-server || true
          sudo docker rm node-server || true

      # Step 5: Run Docker container
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name node-server node-server
